//
// Created by Mirek Škrabal on 17.06.2023.
//

#include "operator_tests.h"

std::vector<Test> operator_tests = {
    TEST("int main() { int i = -2; i = i + 2; return i;}", 0),
    TEST("void main(int a, int b) { 1 * 2; }", 2, true),
    TEST("void main(int a, int b) { a * b; }"),
    TEST("int main(int a, int b) { return a + b; }"),
    TEST("int main(int a, int b) { return a - b; }"),
    TEST("int main(int a, int b) { return a * b; }"),
    TEST("int main(int a, int b) { return a / b; }"),
    TEST("int main(int a, int b) { return a % b; }"),
    TEST("int main(int a, int b) { return a << b; }"),
    TEST("int main(int a, int b) { return a >> b; }"),
    TEST("int main(int a, int b) { return a > b; }"),
    TEST("int main(int a, int b) { return a < b; }"),
    TEST("int main(int a, int b) { return a >= b; }"),
    TEST("int main(int a, int b) { return a <= b; }"),
    TEST("int main(int a, int b) { return a == b; }"),
    TEST("int main(int a, int b) { return a != b; }"),
    TEST("int main(int a, int b) { return a & b; }"),
    TEST("int main(int a, int b) { return a | b; }"),
    TEST("int main(int a, int b) { return a && b; }"),
    TEST("int main(int a, int b) { return a || b; }"),
    TEST("int main(double a, double b) { return a > b; }"),
    TEST("int main(double a, int b) { return a > b; }"),
    TEST("int main(int a, double b) { return a > b; }"),
    TEST("int main(int * a, int * b) { return a > b; }"),
    TEST("double main(int a, double b) { return a + b; }"),
    TEST("int * main(int a, int * b) { return b + a; }"),
    TEST("int main(int i) { return +i; }"),
    TEST("int main(int i) { return -i; }"),
    TEST("int main(int i) { return ~i; }"),
    TEST("int main(int i) { return !i; }"),
    TEST("int main(int i) { return ++i; }"),
    TEST("int main(int i) { return --i; }"),
    TEST("double main(double i) { return +i; }"),
    TEST("double main(double i) { return -i; }"),
    ERROR("double main(double i) { return ~i; }", TypeError),
    TEST("int main(double i) { return !i; }"),
    TEST("double main(double i) { return ++i; }"),
    TEST("double main(double i) { return --i; }"),
    TEST("char main(char i) { return +i; }"),
    TEST("char main(char i) { return -i; }"),
    TEST("char main(char i) { return ~i; }"),
    TEST("int main(char i) { return !i; }"),
    TEST("char main(char i) { return ++i; }"),
    TEST("char main(char i) { return --i; }"),
    ERROR("int * main(int * i) { return +i; }", TypeError),
    ERROR("int * main(int * i) { return -i; }", TypeError),
    ERROR("int * main(int * i) { return ~i; }", TypeError),
    TEST("int main(int * i) { return !i; }"),
    TEST("int * main(int * i) { return ++i; }"),
    TEST("int * main(int * i) { return --i; }"),
    TEST("int main(int argc) { return argc++; }"),
    TEST("double main(double argc) { return argc++; }"),
    TEST("char main(char argc) { return argc++; }"),
    TEST("int * main(int * argc) { return argc++; }"),
    TEST("int main(int argc) { return ++argc; }"),
    TEST("double main(double argc) { return ++argc; }"),
    TEST("char main(char argc) { return ++argc; }"),
    TEST("int * main(int * argc) { return ++argc; }"),
    TEST("void main(int a, int b) { a = 3; }"),
    TEST("void main(int a, int b) { a = b; }"),
};

DEFINE_TEST_CATEGORY(operator_tests)
